import { GlobalBrandingConfig, LandingSectionsData, LandingSectionKey, LegalPagesContent } from '@/types/cms';

export const DEFAULT_SECTION_ORDER: LandingSectionKey[] = [
  'hero',
  'top_categories',
  'master_craft',
  'why_stands_out',
  'real_stories',
  'faq',
  'join_future',
];

export const DEFAULT_BRANDING: GlobalBrandingConfig = {
  logoUrl: '/images/brand-logo.png',
  footerLogoUrl: '/images/brand-logo-white.png',
  faviconUrl: '/favicon.ico',
  siteNameAr: 'كوتش سبيس',
  siteNameEn: 'Coach Space',
  colors: {
    primaryMain: '#0F5244',
    primaryDark: '#07382E',
    primaryLight: '#10B981',
    secondaryLight: '#D1FAE5',
    accentMint: '#34D399',
  },
  buttonRadius: '12px',
  ogImageUrl: '/images/hero-coach.png',
  fontFamilyAr: 'Cairo',
  fontFamilyEn: 'Plus Jakarta Sans',
  customGoogleFontName: '',
  updatedAt: new Date().toISOString(),
  updatedBy: 'system',
};

export const DEFAULT_LANDING_SECTIONS: LandingSectionsData = {
  hero: {
    badge_ar: 'المنصة الرائدة في تمكين الكفاءات',
    badge_en: 'Leading Platform for Career Mastery',
    title_ar: 'انطلق في مسارك نحو',
    title_en: 'Elevate Your Career to',
    highlighted_text_ar: 'الاحتراف والريادة',
    highlighted_text_en: 'True Mastery',
    description_ar: 'اكتشف دورات تدريبية عملية يقودها نخبة من الخبراء والمعتمدين لمساعدتك في بناء مهارات المستقبل وتحقيق أهدافك المهنية.',
    description_en: 'Explore practical, industry-accredited courses led by certified leaders to help you build in-demand skills and accelerate your career.',
    cta_primary_text_ar: 'استكشف الدورات',
    cta_primary_text_en: 'Explore Courses',
    cta_primary_link: '/courses',
    cta_secondary_text_ar: 'انضم كمدرب',
    cta_secondary_text_en: 'Become an Instructor',
    cta_secondary_link: '/become-instructor',
    hero_image_url: '/images/hero-coach.png',
    is_visible: true,
    allowed_roles: ['all'],
  },
  top_categories: {
    title_ar: 'استكشف أبرز المجالات',
    title_en: 'Top In-Demand Categories',
    subtitle_ar: 'تصفح نخبة من التخصصات المصممة لتلبية متطلبات سوق العمل العالمي.',
    subtitle_en: 'Browse our curated collection of specialized programs designed for modern industry requirements.',
    is_visible: true,
    allowed_roles: ['all'],
  },
  master_craft: {
    heading_ar: 'طريقك نحو الإتقان العملي والتميز الوظيفي',
    heading_en: 'Master Practical Craft & Executive Growth',
    description_ar: 'منهجية تدريب تركز على التطبيق العملي وبناء مشاريع واقعية تمنحك ميزة تنافسية حقيقية.',
    description_en: 'Practical methodology focused on real-world projects that give you a tangible edge in the marketplace.',
    features: [
      {
        id: 'feat-1',
        title_ar: 'مشاريع حقيقية معتمدة',
        title_en: 'Accredited Capstone Projects',
        desc_ar: 'قم ببناء محفظة أعمالك المهنية أثناء التعلم من خلال مشاريع حقيقية يتم تقييمها من قِبل خبراء.',
        desc_en: 'Build your verified professional portfolio during study through real-world projects reviewed by industry leaders.',
        icon: 'Award',
      },
      {
        id: 'feat-2',
        title_ar: 'إرشاد وتوجيه فردي',
        title_en: '1-on-1 Mentorship',
        desc_ar: 'تواصل مباشر وجلسات توجيهية مع مدربين متخصصين لتسريع مسار تعلمك.',
        desc_en: 'Direct access and dedicated guidance sessions with certified coaches to accelerate your learning trajectory.',
        icon: 'Users',
      },
      {
        id: 'feat-3',
        title_ar: 'شهادات إتمام موثقة رقمياً',
        title_en: 'Verifiable Digital Credentials',
        desc_ar: 'احصل على شهادات قابلة للتحقق ومشاركتها مع جهات التوظيف وLinkedIn بنقرة واحدة.',
        desc_en: 'Earn digitally authenticated certificates verifiable by recruiters and shareable on LinkedIn with one click.',
        icon: 'ShieldCheck',
      },
    ],
    is_visible: true,
    allowed_roles: ['all'],
  },
  why_stands_out: {
    title_ar: 'لماذا تختار منصة كوتش سبيس؟',
    title_en: 'Why Choose Coach Space?',
    subtitle_ar: 'صممنا بيئة متكاملة تجمع بين سهولة التجربة، عمق المحتوى، والمرونة التامة.',
    subtitle_en: 'Engineered from the ground up to deliver seamless learning, deep expertise, and maximum flexibility.',
    cards: [
      {
        id: 'card-1',
        title_ar: 'مرونة التعلم الذاتي',
        title_en: 'Self-Paced Flexibility',
        desc_ar: 'تعلم في أي وقت ومن أي جهاز بجودة عالية وتجربة مستخدم سلسة.',
        desc_en: 'Study on your own schedule across any device with a fluid, distraction-free interface.',
        icon: 'Clock',
      },
      {
        id: 'card-2',
        title_ar: 'مجتمع شغوف ونشط',
        title_en: 'Vibrant Peer Community',
        desc_ar: 'تبادل الخبرات وتواصل مع شبكة واسعة من المتعلمين والمهنيين.',
        desc_en: 'Collaborate and network with fellow ambitious professionals worldwide.',
        icon: 'Sparkles',
      },
      {
        id: 'card-3',
        title_ar: 'محتوى متجدد باستمرار',
        title_en: 'Constantly Updated Curriculum',
        desc_ar: 'تحديثات دورية للمسارات التعليمية لضمان مواكبة أحدث التقنيات والمعايير.',
        desc_en: 'Continuous curriculum updates ensuring alignment with modern tools and industry standards.',
        icon: 'TrendingUp',
      },
    ],
    is_visible: true,
    allowed_roles: ['all'],
  },
  real_stories: {
    title_ar: 'قصص نجاح من واقع التجربة',
    title_en: 'Real Stories from Our Learners',
    subtitle_ar: 'آراء وتجارب ملهمة من خريجين ارتقوا بمساراتهم المهنية معنا.',
    subtitle_en: 'Inspiring achievements and testimonials from alumni who transformed their careers.',
    testimonials: [
      {
        id: 't-1',
        name_ar: 'سارة المنصوري',
        name_en: 'Sara Al-Mansouri',
        role_ar: 'مديرة تسويق رقمي',
        role_en: 'Senior Digital Marketing Lead',
        quote_ar: 'المحتوى العملي والمشاريع الواقعية ساعدتني على الترقية وتولي قيادة الفريق خلال 4 أشهر فقط!',
        quote_en: 'The practical capstones and mentor feedback enabled me to step into a leadership role within 4 months!',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 't-2',
        name_ar: 'عمر الهاشمي',
        name_en: 'Omar Al-Hashemi',
        role_ar: 'مطور برمجيات سحابية',
        role_en: 'Cloud Software Engineer',
        quote_ar: 'التوجيه المباشر وجودة المنهاج كانت نقطة التحول الحقيقية في فهمي للأنظمة الموزعة.',
        quote_en: 'The direct feedback from coaches was the defining breakthrough in mastering distributed architectures.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 't-3',
        name_ar: 'ليلى الكردي',
        name_en: 'Layla Al-Kurdi',
        role_ar: 'مصممة تجربة مستخدم',
        role_en: 'Product Designer',
        quote_ar: 'أفضل استثمار قمت به في مسيرتي، الشهادة الموثقة نالت ثقة الشركات العالمية فوراً.',
        quote_en: 'Best investment in my growth; the authenticated credential gave me instant credibility with employers.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 't-4',
        name_ar: 'فيصل السالم',
        name_en: 'Faisal Al-Salem',
        role_ar: 'محلل بيانات أول',
        role_en: 'Lead Data Analyst',
        quote_ar: 'الدورة مكّنتني من بناء نماذج تحليلية واقعية وتطبيقها مباشرة في بيئة عملي الحالية بكفاءة واحتراف.',
        quote_en: 'The coursework empowered me to build production analytics models applied directly to my workplace.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      },
    ],
    is_visible: true,
    allowed_roles: ['all'],
  },
  faq: {
    title_ar: 'الأسئلة الشائعة',
    title_en: 'Frequently Asked Questions',
    subtitle_ar: 'إليك إجابات لأهم الاستفسارات حول الدورات وطريقة التعلم والشهادات.',
    subtitle_en: 'Clear answers to common questions about courses, learning experience, and certificates.',
    items: [
      {
        id: 'faq-1',
        question_ar: 'كيف أبدأ التعلم في منصة كوتش سبيس؟',
        question_en: 'How do I start learning on Coach Space?',
        answer_ar: 'يمكنك إنشاء حساب مجاناً، تصفح الكتالوج، واختيار الدورة المناسبة والبدء فوراً في حضور الدروس التفاعلية.',
        answer_en: 'Simply register for a free account, explore the catalog, enroll in your chosen course, and start learning immediately.',
      },
      {
        id: 'faq-2',
        question_ar: 'هل الشهادات الصادرة معتمدة وموثقة؟',
        question_en: 'Are certificates officially accredited and verifiable?',
        answer_ar: 'نعم، تصدر المنصة شهادة إتمام رقمية برمز تحقق فريد (QR Code ورقم تسلسلي) يمكن لأي جهة توظيف التحقق من صحتها فوراً.',
        answer_en: 'Yes, every completed course awards a tamper-proof credential with a unique verification code and QR code for employers.',
      },
      {
        id: 'faq-3',
        question_ar: 'هل يمكنني استرجاع الرسوم إذا لم تناسبني الدورة؟',
        question_en: 'What is the refund policy?',
        answer_ar: 'نعم، نقدم ضمان استرجاع كامل الرسوم خلال 14 يوماً من تاريخ الشراء في حال عدم تجاوز نسبة معينة من المحتوى.',
        answer_en: 'Yes, we offer a 14-day money-back guarantee if you have not completed more than the trial portion of the coursework.',
      },
      {
        id: 'faq-4',
        question_ar: 'كيف يمكنني الانضمام كمدرب وتقديم دوراتي؟',
        question_en: 'How can I join as an instructor?',
        answer_ar: 'يمكنك الضغط على زر "انضم كمدرب" وتعبئة الطلب وتقديم نبذة عن خبراتك، وسيتواصل معك فريقنا لاعتماد حسابك وبدء رفع الكورسات.',
        answer_en: 'Click "Become an Instructor", submit your credentials and experience, and our team will review and approve your studio access.',
      },
    ],
    is_visible: true,
    allowed_roles: ['all'],
  },
  join_future: {
    title_ar: 'هل أنت مستعد لبدء خطوتك القادمة؟',
    title_en: 'Ready to Take Your Next Giant Leap?',
    subtitle_ar: 'انضم اليوم إلى آلاف المتعلمين والخبراء وابدأ في كتابة قصة نجاحك الجديدة.',
    subtitle_en: 'Join thousands of ambitious professionals and start shaping your success today.',
    button_text_ar: 'ابدأ التعلم الآن مجاناً',
    button_text_en: 'Get Started for Free',
    button_link: '/register',
    is_visible: true,
    allowed_roles: ['all'],
  },
  section_order: DEFAULT_SECTION_ORDER,
  views: {
    guest: {
      hero: {
        badge_ar: 'المنصة الرائدة في تمكين الكفاءات',
        badge_en: 'Leading Platform for Career Mastery',
        title_ar: 'انطلق في مسارك نحو',
        title_en: 'Elevate Your Career to',
        highlighted_text_ar: 'الاحتراف والريادة',
        highlighted_text_en: 'True Mastery',
        description_ar: 'اكتشف دورات تدريبية عملية يقودها نخبة من الخبراء والمعتمدين لمساعدتك في بناء مهارات المستقبل وتحقيق أهدافك المهنية.',
        description_en: 'Explore practical, industry-accredited courses led by certified leaders to help you build in-demand skills and accelerate your career.',
        cta_primary_text_ar: 'استكشف الدورات',
        cta_primary_text_en: 'Explore Courses',
        cta_primary_link: '/courses',
        cta_secondary_text_ar: 'انضم كمدرب',
        cta_secondary_text_en: 'Become an Instructor',
        cta_secondary_link: '/become-instructor',
        hero_image_url: '/images/hero-coach.png',
        is_visible: true,
        allowed_roles: ['all'],
      },
      top_categories: {
        title_ar: 'استكشف أبرز المجالات',
        title_en: 'Top In-Demand Categories',
        subtitle_ar: 'تصفح نخبة من التخصصات المصممة لتلبية متطلبات سوق العمل العالمي.',
        subtitle_en: 'Browse our curated collection of specialized programs designed for modern industry requirements.',
        is_visible: true,
        allowed_roles: ['all'],
      },
      master_craft: {
        heading_ar: 'طريقك نحو الإتقان العملي والتميز الوظيفي',
        heading_en: 'Master Practical Craft & Executive Growth',
        description_ar: 'منهجية تدريب تركز على التطبيق العملي وبناء مشاريع واقعية تمنحك ميزة تنافسية حقيقية.',
        description_en: 'Practical methodology focused on real-world projects that give you a tangible edge in the marketplace.',
        features: [
          {
            id: 'feat-1',
            title_ar: 'مشاريع حقيقية معتمدة',
            title_en: 'Accredited Capstone Projects',
            desc_ar: 'قم ببناء محفظة أعمالك المهنية أثناء التعلم من خلال مشاريع حقيقية يتم تقييمها من قِبل خبراء.',
            desc_en: 'Build your verified professional portfolio during study through real-world projects reviewed by industry leaders.',
            icon: 'Award',
          },
          {
            id: 'feat-2',
            title_ar: 'إرشاد وتوجيه فردي',
            title_en: '1-on-1 Mentorship',
            desc_ar: 'تواصل مباشر وجلسات توجيهية مع مدربين متخصصين لتسريع مسار تعلمك.',
            desc_en: 'Direct access and dedicated guidance sessions with certified coaches to accelerate your learning trajectory.',
            icon: 'Users',
          },
          {
            id: 'feat-3',
            title_ar: 'شهادات إتمام موثقة رقمياً',
            title_en: 'Verifiable Digital Credentials',
            desc_ar: 'احصل على شهادات قابلة للتحقق ومشاركتها مع جهات التوظيف وLinkedIn بنقرة واحدة.',
            desc_en: 'Earn digitally authenticated certificates verifiable by recruiters and shareable on LinkedIn with one click.',
            icon: 'ShieldCheck',
          },
        ],
        is_visible: true,
        allowed_roles: ['all'],
      },
      why_stands_out: {
        title_ar: 'لماذا تختار منصة كوتش سبيس؟',
        title_en: 'Why Choose Coach Space?',
        subtitle_ar: 'صممنا بيئة متكاملة تجمع بين سهولة التجربة، عمق المحتوى، والمرونة التامة.',
        subtitle_en: 'Engineered from the ground up to deliver seamless learning, deep expertise, and maximum flexibility.',
        cards: [
          {
            id: 'card-1',
            title_ar: 'مرونة التعلم الذاتي',
            title_en: 'Self-Paced Flexibility',
            desc_ar: 'تعلم في أي وقت ومن أي جهاز بجودة عالية وتجربة مستخدم سلسة.',
            desc_en: 'Study on your own schedule across any device with a fluid, distraction-free interface.',
            icon: 'Clock',
          },
          {
            id: 'card-2',
            title_ar: 'مجتمع شغوف ونشط',
            title_en: 'Vibrant Peer Community',
            desc_ar: 'تبادل الخبرات وتواصل مع شبكة واسعة من المتعلمين والمهنيين.',
            desc_en: 'Collaborate and network with fellow ambitious professionals worldwide.',
            icon: 'Sparkles',
          },
          {
            id: 'card-3',
            title_ar: 'محتوى متجدد ومواكب',
            title_en: 'Cutting-Edge Curriculum',
            desc_ar: 'مناهج يتم تحديثها باستمرار لتغطي أحدث التقنيات وأفضل الممارسات العملية.',
            desc_en: 'Constantly updated course materials reflecting the latest technical standards and real workflows.',
            icon: 'Compass',
          },
        ],
        is_visible: true,
        allowed_roles: ['all'],
      },
      real_stories: {
        title_ar: 'قصص نجاح وتجارب حقيقية',
        title_en: 'Real Success Stories from Our Learners',
        subtitle_ar: 'استمع إلى آراء وتجارب خريجينا وكيف ساعدتهم منصة كوتش سبيس في تحقيق نقلات نوعية في مسيرتهم المهنية.',
        subtitle_en: 'Hear directly from our graduates on how Coach Space helped accelerate their career milestones.',
        testimonials: [
          {
            id: 'story-1',
            name_ar: 'سارة الأحمد',
            name_en: 'Sarah Al-Ahmad',
            role_ar: 'مديرة منتجات رقمية',
            role_en: 'Digital Product Lead',
            quote_ar: 'منهجية المشاريع الواقعية في كوتش سبيس منحتني الثقة للتقدم لوظيفة قيادية في إحدى كبرى الشركات التقنية.',
            quote_en: 'The capstone projects gave me the practical confidence to step into a leadership product role at a top tech enterprise.',
            rating: 5,
          },
          {
            id: 'story-2',
            name_ar: 'عمر القحطاني',
            name_en: 'Omar Al-Qahtani',
            role_ar: 'مهندس ذكاء اصطناعي',
            role_en: 'AI Solutions Engineer',
            quote_ar: 'التوجيه المباشر من المدربين وفر عليّ أشهراً من المحاولات العشوائية. المحتوى هنا احترافي جداً.',
            quote_en: '1-on-1 mentorship saved me months of trial and error. The curricula are intensely focused and cutting-edge.',
            rating: 5,
          },
          {
            id: 'story-3',
            name_ar: 'ليلى المنصور',
            name_en: 'Laila Al-Mansoor',
            role_ar: 'مصممة واجهات تجربة مستخدم',
            role_en: 'Senior UX Architect',
            quote_ar: 'أفضل استثمار في مسيرتي المهنية. استطعت بناء بورتفوليو قوي تم اعتماده من جهات التوظيف فوراً.',
            quote_en: 'The single best investment in my career. I built a bulletproof portfolio that instantly won over recruiters.',
            rating: 5,
          },
          {
            id: 'story-4',
            name_ar: 'فيصل السالم',
            name_en: 'Faisal Al-Salem',
            role_ar: 'محلل بيانات أول',
            role_en: 'Lead Data Analyst',
            quote_ar: 'الدورة مكّنتني من بناء نماذج تحليلية واقعية وتطبيقها مباشرة في بيئة عملي الحالية بكفاءة واحتراف.',
            quote_en: 'The coursework empowered me to build production analytics models applied directly to my workplace.',
            rating: 5,
          },
        ],
        is_visible: true,
        allowed_roles: ['all'],
      },
      faq: {
        title_ar: 'الأسئلة الشائعة حول المنصة',
        title_en: 'Frequently Asked Questions',
        subtitle_ar: 'إجابات واضحة ومباشرة عن كافة التساؤلات المتعلقة بالدورات والشهادات وآلية التعلم.',
        subtitle_en: 'Clear and comprehensive answers to the most common questions regarding courses and certification.',
        items: [
          {
            id: 'faq-1',
            question_ar: 'كيف أصل إلى الدورات بعد إتمام عملية التسجيل؟',
            question_en: 'How do I access courses after registration?',
            answer_ar: 'ستتمكن فوراً من الوصول لجميع مواد الدورة ومجتمع المتعلمين عبر لوحة تحكم الطالب الخاصة بك بنقرة واحدة.',
            answer_en: 'You receive instant lifetime access to all learning materials, exercises, and the peer community from your Student Dashboard.',
          },
          {
            id: 'faq-2',
            question_ar: 'هل الشهادات الصادرة من كوتش سبيس معتمدة وموثقة؟',
            question_en: 'Are certificates officially accredited and verifiable?',
            answer_ar: 'نعم، تصدر المنصة شهادة إتمام رقمية برمز تحقق فريد (QR Code ورقم تسلسلي) يمكن لأي جهة توظيف التحقق من صحتها فوراً.',
            answer_en: 'Yes, every completed course awards a tamper-proof credential with a unique verification code and QR code for employers.',
          },
          {
            id: 'faq-3',
            question_ar: 'هل يمكنني استرجاع الرسوم إذا لم تناسبني الدورة؟',
            question_en: 'What is the refund policy?',
            answer_ar: 'نعم، نقدم ضمان استرجاع كامل الرسوم خلال 14 يوماً من تاريخ الشراء في حال عدم تجاوز نسبة معينة من المحتوى.',
            answer_en: 'Yes, we offer a 14-day money-back guarantee if you have not completed more than the trial portion of the coursework.',
          },
          {
            id: 'faq-4',
            question_ar: 'كيف يمكنني الانضمام كمدرب وتقديم دوراتي؟',
            question_en: 'How can I join as an instructor?',
            answer_ar: 'يمكنك الضغط على زر "انضم كمدرب" وتعبئة الطلب وتقديم نبذة عن خبراتك، وسيتواصل معك فريقنا لاعتماد حسابك وبدء رفع الكورسات.',
            answer_en: 'Click "Become an Instructor", submit your credentials and experience, and our team will review and approve your studio access.',
          },
        ],
        is_visible: true,
        allowed_roles: ['all'],
      },
      join_future: {
        title_ar: 'هل أنت مستعد لبدء خطوتك القادمة؟',
        title_en: 'Ready to Take Your Next Giant Leap?',
        subtitle_ar: 'انضم اليوم إلى آلاف المتعلمين والخبراء وابدأ في كتابة قصة نجاحك الجديدة.',
        subtitle_en: 'Join thousands of ambitious professionals and start shaping your success today.',
        button_text_ar: 'انضم كمدرب الآن',
        button_text_en: 'Become an Instructor',
        button_link: '/become-instructor',
        is_visible: true,
        allowed_roles: ['all'],
      },
      section_order: ['hero', 'top_categories', 'master_craft', 'why_stands_out', 'real_stories', 'faq', 'join_future'],
    },
    student: {
      hero: {
        badge_ar: 'مرحباً بك مجدداً في رحلتك التعليمية',
        badge_en: 'Welcome Back to Your Learning Journey',
        title_ar: 'واصل بناء مهاراتك وانطلق نحو',
        title_en: 'Continue Building Skills Toward',
        highlighted_text_ar: 'أهدافك وطموحاتك المهنية',
        highlighted_text_en: 'Your Professional Goals',
        description_ar: 'تابع تقدمك في الدورات المسجلة، استكشف التخصصات الجديدة المعتمدة، واحصل على شهادات موثقة تعزز سيرتك المهنية.',
        description_en: 'Track your course progress, explore newly accredited tracks, and earn verifiable certificates to power your career.',
        cta_primary_text_ar: 'متابعة دوراتي',
        cta_primary_text_en: 'Continue My Courses',
        cta_primary_link: '/student/courses',
        cta_secondary_text_ar: 'استكشف مسارات جديدة',
        cta_secondary_text_en: 'Explore New Tracks',
        cta_secondary_link: '/courses',
        hero_image_url: '/images/hero-coach.png',
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      top_categories: {
        title_ar: 'مسارات وتصنيفات التعلم الموصى بها',
        title_en: 'Recommended Learning Tracks',
        subtitle_ar: 'اختر تخصصك القادم واستكمل بناء محفظة مهاراتك التطبيقية.',
        subtitle_en: 'Select your next track and expand your practical skill portfolio.',
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      master_craft: {
        heading_ar: 'تطوير المهارات التطبيقية والمشاريع المعتمدة',
        heading_en: 'Hands-on Skill Mastery & Real Projects',
        description_ar: 'فرصتك لتطبيق ما تعلمته نظرياً على مشاريع واقعية تقيم بإشراف نخبة من الخبراء.',
        description_en: 'Apply your knowledge through verified capstone projects supervised by industry mentors.',
        features: [
          {
            id: 'feat-s1',
            title_ar: 'مشاريع حقيقية معتمدة',
            title_en: 'Accredited Capstone Projects',
            desc_ar: 'قم ببناء محفظة أعمالك المهنية أثناء التعلم من خلال مشاريع حقيقية يتم تقييمها من قِبل خبراء.',
            desc_en: 'Build your verified professional portfolio during study through real-world projects reviewed by industry leaders.',
            icon: 'Award',
          },
          {
            id: 'feat-s2',
            title_ar: 'إرشاد وتوجيه فردي مستمر',
            title_en: 'Ongoing Mentorship',
            desc_ar: 'تواصل مباشر مع مدربيك للحصول على تقييمات دقيقة لأعمالك.',
            desc_en: 'Direct access to mentors for actionable feedback on your submissions.',
            icon: 'Users',
          },
          {
            id: 'feat-s3',
            title_ar: 'شهادات إتمام موثقة رقمياً',
            title_en: 'Verifiable Digital Credentials',
            desc_ar: 'احصل على شهادات قابلة للتحقق ومشاركتها مع جهات التوظيف وLinkedIn بنقرة واحدة.',
            desc_en: 'Earn digitally authenticated certificates verifiable by recruiters and shareable on LinkedIn with one click.',
            icon: 'ShieldCheck',
          },
        ],
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      why_stands_out: {
        title_ar: 'مزايا تجربة التعلم في كوتش سبيس',
        title_en: 'Student Platform Advantages',
        subtitle_ar: 'أدوات صممت خصيصاً لتيسير رحلتك ودعم استمرارية تعلمك.',
        subtitle_en: 'Features tailored to accelerate your mastery and engagement.',
        cards: [
          {
            id: 'card-s1',
            title_ar: 'مرونة التعلم الذاتي',
            title_en: 'Self-Paced Flexibility',
            desc_ar: 'تعلم في أي وقت ومن أي جهاز بجودة عالية وتجربة مستخدم سلسة.',
            desc_en: 'Study on your own schedule across any device with a fluid, distraction-free interface.',
            icon: 'Clock',
          },
          {
            id: 'card-s2',
            title_ar: 'مجتمع زملاء نشط',
            title_en: 'Vibrant Peer Community',
            desc_ar: 'تبادل الخبرات وتواصل مع شبكة واسعة من المتعلمين والمهنيين.',
            desc_en: 'Collaborate and network with fellow ambitious professionals worldwide.',
            icon: 'Sparkles',
          },
          {
            id: 'card-s3',
            title_ar: 'محتوى متجدد ومواكب',
            title_en: 'Cutting-Edge Curriculum',
            desc_ar: 'مناهج يتم تحديثها باستمرار لتغطي أحدث التقنيات وأفضل الممارسات العملية.',
            desc_en: 'Constantly updated course materials reflecting the latest technical standards and real workflows.',
            icon: 'Compass',
          },
        ],
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      real_stories: {
        title_ar: 'تجارب وقصص نجاح الزملاء',
        title_en: 'Peer Success Stories',
        subtitle_ar: 'تعرف على كيف حقق زملاؤك أهدافهم المهنية بعد إتمام المسارات.',
        subtitle_en: 'Discover how fellow students unlocked opportunities through Coach Space.',
        testimonials: [
          {
            id: 'story-s1',
            name_ar: 'سارة الأحمد',
            name_en: 'Sarah Al-Ahmad',
            role_ar: 'مديرة منتجات رقمية',
            role_en: 'Digital Product Lead',
            quote_ar: 'منهجية المشاريع الواقعية في كوتش سبيس منحتني الثقة للتقدم لوظيفة قيادية في إحدى كبرى الشركات التقنية.',
            quote_en: 'The capstone projects gave me the practical confidence to step into a leadership product role at a top tech enterprise.',
            rating: 5,
          },
          {
            id: 'story-s2',
            name_ar: 'عمر القحطاني',
            name_en: 'Omar Al-Qahtani',
            role_ar: 'مهندس ذكاء اصطناعي',
            role_en: 'AI Solutions Engineer',
            quote_ar: 'التوجيه المباشر من المدربين وفر عليّ أشهراً من المحاولات العشوائية. المحتوى هنا احترافي جداً.',
            quote_en: '1-on-1 mentorship saved me months of trial and error. The curricula are intensely focused and cutting-edge.',
            rating: 5,
          },
          {
            id: 'story-s3',
            name_ar: 'ليلى الغامدي',
            name_en: 'Layla Al-Ghamdi',
            role_ar: 'مصممة واجهات وتجربة مستخدم',
            role_en: 'Senior UI/UX Designer',
            quote_ar: 'التقييمات التفصيلية من المدرب على مشروعي النهائي كانت العامل الأساسي في حصولي على وظيفة أحلامي.',
            quote_en: 'The in-depth mentor reviews on my capstone project were the decisive catalyst for landing my dream role.',
            rating: 5,
          },
          {
            id: 'story-s4',
            name_ar: 'خالد المنصور',
            name_en: 'Khaled Al-Mansour',
            role_ar: 'مطور تطبيقات سحابية متقدمة',
            role_en: 'Full-Stack Cloud Developer',
            quote_ar: 'تجربة التعلم التطبيقي والشهادة الموثقة برمز QR فتحت لي أبواب التعاقد مع عملاء دوليين بكل ثقة.',
            quote_en: 'The hands-on coursework and verifiable QR credential granted me instant credibility with international enterprise clients.',
            rating: 5,
          },
        ],
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      faq: {
        title_ar: 'أسئلة واستفسارات الطلاب الشائعة',
        title_en: 'Student Frequently Asked Questions',
        subtitle_ar: 'إجابات حول متابعة الدورات، الاختبارات، وإصدار الشهادات المعتمدة.',
        subtitle_en: 'Answers regarding course progress, assessments, and verifiable certification.',
        items: [
          {
            id: 'faq-s1',
            question_ar: 'كيف أصل إلى شهادة الإتمام بعد إنهاء الدورة؟',
            question_en: 'How do I obtain my certificate upon completion?',
            answer_ar: 'بمجرد إنهاء كافة دروس واختبارات الدورة، ستجد شهادتك جاهزة للتحميل والمشاركة مباشرة في صفحة "شهاداتي".',
            answer_en: 'Once all lessons and assessments are 100% complete, your certificate is instantly available in your "Certificates" tab.',
          },
          {
            id: 'faq-s2',
            question_ar: 'هل يمكنني التواصل مع المدرب لطرح الأسئلة؟',
            question_en: 'Can I directly interact with the instructor?',
            answer_ar: 'نعم، تحتوي كل دورة على قسم نقاشات وتواصل مخصص للأسئلة مع المدرب والزملاء.',
            answer_en: 'Yes, each course features a dedicated Q&A and discussion area to communicate with instructors and peers.',
          },
        ],
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      join_future: {
        title_ar: 'هل ترغب في مشاركة خبراتك والبدء بالتدريس؟',
        title_en: 'Ready to Share Your Expertise & Start Teaching?',
        subtitle_ar: 'انضم إلى مجتمع الخبراء والمدربين في كوتش سبيس، وحوّل معرفتك إلى دورات معتمدة ومصدر دخل مستدام.',
        subtitle_en: 'Join our community of elite coaches, transform your knowledge into accredited courses, and earn a steady income.',
        button_text_ar: 'انضم كمدرب الآن',
        button_text_en: 'Become an Instructor',
        button_link: '/become-instructor',
        is_visible: true,
        allowed_roles: ['student', 'all'],
      },
      section_order: ['hero', 'top_categories', 'master_craft', 'why_stands_out', 'real_stories', 'faq', 'join_future'],
    },
    instructor: {
      hero: {
        badge_ar: 'استوديو المدربين والخبراء المعتمدين',
        badge_en: 'Certified Instructor Studio',
        title_ar: 'شارك خبراتك وقد أجيال المستقبل مع',
        title_en: 'Share Your Expertise & Lead the Future with',
        highlighted_text_ar: 'استوديو كوتش سبيس',
        highlighted_text_en: 'Coach Space Studio',
        description_ar: 'لوحة تحكم ذكية تمنحك أدوات متطورة لإنشاء الدورات، متابعة تفاعل الطلاب، وتحقيق عوائد مجزية بكل سهولة وموثوقية.',
        description_en: 'Smart dashboard equipped with advanced tools to build courses, monitor student engagement, and scale your teaching impact.',
        cta_primary_text_ar: 'الذهاب إلى الاستوديو',
        cta_primary_text_en: 'Go to Studio',
        cta_primary_link: '/instructor/dashboard',
        cta_secondary_text_ar: 'إنشاء دورة جديدة',
        cta_secondary_text_en: 'Create New Course',
        cta_secondary_link: '/instructor/courses/new',
        hero_image_url: '/images/hero-coach.png',
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      top_categories: {
        title_ar: 'المجالات والتخصصات الأكثر طلباً للتدريس',
        title_en: 'High-Demand Teaching Disciplines',
        subtitle_ar: 'اكتشف أكثر التخصصات والمهارات التي يبحث عنها آلاف الطلاب بالمنصة لبدء إعداد دوراتك بها.',
        subtitle_en: 'Discover the most requested disciplines and skills our students are eager to master.',
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      master_craft: {
        heading_ar: 'أدوات وتقنيات متقدمة لإدارة ونشر دوراتك الاحترافية',
        heading_en: 'Advanced Tools to Build, Scale & Manage Your Courses',
        description_ar: 'نوفر لك استوديو متكامل يجمع بين سهولة رفع المحتوى، التحليلات اللحظية لتفاعل الطلاب، وإصدار الشهادات المعتمدة.',
        description_en: 'A comprehensive instructor suite featuring intuitive course builders, real-time student analytics, and automated verified certifications.',
        features: [
          {
            id: 'feat-inst-1',
            title_ar: 'استوديو رفع وتنظيم ذكي',
            title_en: 'Smart Course Builder Studio',
            desc_ar: 'قم برفع مقاطع الفيديو والملفات المرفقة وتنسيق الفصول بسلاسة وسرعة فائقة.',
            desc_en: 'Upload high-definition video lessons, workbooks, and structure modules with ease.',
          },
          {
            id: 'feat-inst-2',
            title_ar: 'لوحة تحليلات وإيرادات دقيقة',
            title_en: 'Real-Time Analytics & Earnings',
            desc_ar: 'متابعة فورية لمعدلات إكمال الطلاب، التقييمات، والأرباح الشهرية مع تفاصيل السحب المباشر.',
            desc_en: 'Track student completion rates, reviews, and monthly revenue with direct bank deposits.',
          },
          {
            id: 'feat-inst-3',
            title_ar: 'نظام اختبارات وشهادات رقمية موثقة',
            title_en: 'Interactive Quizzes & Verified Credentials',
            desc_ar: 'إعداد بنك أسئلة واختبارات تصدر شهادات معتمدة برمز تحقق فوري QR Code لكل طالب ناجح.',
            desc_en: 'Construct custom quizzes and issue automated, tamper-proof verifiable credentials.',
          },
          {
            id: 'feat-inst-4',
            title_ar: 'غرف نقاش وتفاعل مباشر',
            title_en: 'Direct Student Engagement',
            desc_ar: 'تواصل مع المتعلمين وأجب عن استفساراتهم وابنِ مجتمعاً معرفياً نشطاً حول علامتك التدريبية.',
            desc_en: 'Foster active learning through dedicated Q&A hubs and direct student messaging.',
          },
        ],
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      why_stands_out: {
        title_ar: 'لماذا يختار كبار الخبراء التدريس عبر كوتش سبيس؟',
        title_en: 'Why Industry Leaders Choose to Teach on Coach Space',
        subtitle_ar: 'منظومة متكاملة تضمن حماية ملكيتك الفكرية، انتشاراً واسعاً، وعوائد مالية مجزية ومستقرة.',
        subtitle_en: 'An ecosystem built to safeguard your intellectual property, maximize your reach, and guarantee reliable payouts.',
        cards: [
          {
            id: 'card-inst-1',
            title_ar: 'عوائد مالية مجزية ومستقرة',
            title_en: 'Competitive & Predictable Earnings',
            desc_ar: 'نظام تسعير مرن وعوائد دورية شفافة تُحوّل مباشرة لحسابك البنكي دون تعقيدات.',
            desc_en: 'Flexible pricing models and transparent monthly payouts deposited directly into your bank.',
          },
          {
            id: 'card-inst-2',
            title_ar: 'حماية تامة للمحتوى والملكية',
            title_en: 'Advanced Content Protection',
            desc_ar: 'تقنيات تشفير لمنع القرصنة وتسريب الفيديوهات وحماية علامتك التجارية التدريبية.',
            desc_en: 'State-of-the-art DRM encryption preventing unauthorized downloads and piracy.',
          },
          {
            id: 'card-inst-3',
            title_ar: 'حملات تسويقية وترويجية موجهة',
            title_en: 'Targeted Audience Marketing',
            desc_ar: 'نروج لدوراتك التدريبية لآلاف الكفاءات والشركات الباحثة عن خبراتك وتخصصك.',
            desc_en: 'Dedicated marketing campaigns positioning your courses before thousands of eager learners.',
          },
          {
            id: 'card-inst-4',
            title_ar: 'دعم فني واستشاري على مدار الساعة',
            title_en: 'Dedicated Pedagogical Support',
            desc_ar: 'فريق متخصص لمساعدتك في مراجعة جودة الصوت والصورة وتحسين خطة ودليل الدورة.',
            desc_en: 'Our instructional design team helps you optimize curriculum, audio, and production quality.',
          },
        ],
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      real_stories: {
        title_ar: 'قصص نجاح وتجارب ملهمة لمدربينا',
        title_en: 'Inspiring Journeys from Our Leading Coaches',
        subtitle_ar: 'تعرف على كيفية مساهمة كوتش سبيس في تمكين الخبراء من بناء علاماتهم التدريبية وتدريب آلاف المتعلمين.',
        subtitle_en: 'Discover how industry veterans transformed their expertise into thriving academies on Coach Space.',
        testimonials: [
          {
            id: 'story-inst-1',
            name_ar: 'د. طارق السعيد',
            name_en: 'Dr. Tariq Al-Saeed',
            role_ar: 'خبير استشارات قيادية وإدارية',
            role_en: 'Executive Leadership Consultant',
            quote_ar: 'منصة كوتش سبيس وفّرت لي بيئة تعليمية تضاهي المعايير العالمية. تمكنت من تدريب أكثر من 12,000 متخصص في عام واحد بكل يسر واحترافية.',
            quote_en: 'Coach Space provided world-class infrastructure. I empowered over 12,000 professionals in a single year with seamless delivery.',
            rating: 5,
          },
          {
            id: 'story-inst-2',
            name_ar: 'م. ريم الناصر',
            name_en: 'Eng. Reem Al-Nasser',
            role_ar: 'مهندسة حلول سحابية وذكاء اصطناعي',
            role_en: 'Cloud Solutions & AI Architect',
            quote_ar: 'أكثر ما يميز المنصة هو وضوح التقارير وسرعة تحويل المستحقات وحماية المحتوى، مما جعلني أركز تماماً على تقديم أعلى قيمة لطلابي.',
            quote_en: 'Transparent payouts, robust content security, and granular analytics let me focus 100% on delivering stellar educational value.',
            rating: 5,
          },
          {
            id: 'story-inst-3',
            name_ar: 'أ.د. فيصل الزهراني',
            name_en: 'Prof. Faisal Al-Zahrani',
            role_ar: 'أستاذ علوم الحاسب واستشاري تعليمي',
            role_en: 'Computer Science Professor & Mentor',
            quote_ar: 'أدوات إعداد الاختبارات التفاعلية والتحليلات اللحظية لإكمال الدروس ساعدتني على رفع نسبة التفاعل والإكمال إلى أكثر من 90% بين طلابي.',
            quote_en: 'Interactive testing and real-time completion analytics helped me achieve over 90% engagement across my specialized cohorts.',
            rating: 5,
          },
          {
            id: 'story-inst-4',
            name_ar: 'د. منى الحربي',
            name_en: 'Dr. Mona Al-Harbi',
            role_ar: 'مستشارة تميز مؤسسي وقيادي',
            role_en: 'Organizational Leadership Consultant',
            quote_ar: 'المنصة أتاحت لي بناء أكاديمية متكاملة لبرامجي التدريبية مع حماية تامة للمحتوى ودعم فني استثنائي وتجربة دفع مرنة للمشتركين.',
            quote_en: 'Coach Space enabled me to launch a full-scale academy with airtight content protection, stellar support, and frictionless student enrollments.',
            rating: 5,
          },
        ],
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      faq: {
        title_ar: 'الأسئلة الشائعة للمدربين والخبراء',
        title_en: 'Instructor Frequently Asked Questions',
        subtitle_ar: 'كل ما تحتاج لمعرفته حول إنشاء الدورات، سياسات القبول، ونظام الأرباح والمدفوعات.',
        subtitle_en: 'Everything you need to know about course creation, verification, and payout systems.',
        items: [
          {
            id: 'faq-inst-1',
            question_ar: 'كيف أبدأ بنشر أول دورة تدريبية لي؟',
            question_en: 'How do I start publishing my first course?',
            answer_ar: 'يمكنك التوجه إلى استوديو الدورات، والضغط على "إنشاء دورة جديدة"، ثم ملء التفاصيل ورفع الدروس وإرسالها للمراجعة والاعتماد.',
            answer_en: 'Go to the Course Studio, click "Create New Course", fill in details, upload curriculum lessons, and submit for verification.',
          },
          {
            id: 'faq-inst-2',
            question_ar: 'متى وكيف يتم تحويل أرباح ومستحقات المدرب؟',
            question_en: 'When and how are instructor payouts processed?',
            answer_ar: 'تُحوّل الأرباح شهرياً عبر الحساب البنكي المسجل أو الطرق المعتمدة عند وصول الحد الأدنى للسحب بعد معالجة فترات الضمان.',
            answer_en: 'Payouts are processed on a monthly schedule via registered bank transfer once minimum thresholds are met.',
          },
          {
            id: 'faq-inst-3',
            question_ar: 'ما هي معايير الجودة والاعتماد المطلوبة للدورات؟',
            question_en: 'What are the quality and accreditation standards for courses?',
            answer_ar: 'يشترط وضوح الصوت والصورة، حداثة المحتوى العلمي، وتقديم قيمة تطبيقية ملموسة للمتعلمين مع مشاريع عملية.',
            answer_en: 'Requirements include high-definition audio/video, up-to-date practical content, and actionable projects for students.',
          },
          {
            id: 'faq-inst-4',
            question_ar: 'هل أحتفظ بحقوق الملكية الفكرية لمحتوى دوراتي؟',
            question_en: 'Do I retain full intellectual property rights to my courses?',
            answer_ar: 'نعم بالتأكيد، تحتفظ بكامل ملكيتك الفكرية للمحتوى التعليمي وتمنح المنصة فقط ترخيصاً لعرض الدورة للطلاب المسجلين.',
            answer_en: 'Yes, absolutely. You retain 100% intellectual property ownership of your content, granting only a distribution license.',
          },
        ],
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      join_future: {
        title_ar: 'هل أنت مستعد لمضاعفة أثرك وبدء دورتك القادمة؟',
        title_en: 'Ready to Amplify Your Impact with Your Next Course?',
        subtitle_ar: 'استفد من أدوات الذكاء الاصطناعي والاستوديو الحديث لإطلاق دورات بمعايير عالمية خلال دقائق.',
        subtitle_en: 'Leverage our AI tools and modern studio to launch accredited courses in record time.',
        button_text_ar: 'الانتقال إلى استوديو الدورات',
        button_text_en: 'Go to Course Studio',
        button_link: '/instructor/dashboard',
        is_visible: true,
        allowed_roles: ['instructor', 'all'],
      },
      section_order: ['hero', 'top_categories', 'master_craft', 'why_stands_out', 'real_stories', 'faq', 'join_future'],
    },
  },
};

export const DEFAULT_LEGAL_PAGES: LegalPagesContent = {
  privacy: {
    badge_ar: 'الشفافية والأمان',
    badge_en: 'Trust & Transparency',
    title_ar: 'سياسة الخصوصية',
    title_en: 'Privacy Policy',
    subtitle_ar: 'نلتزم في منصة Coach Space بحماية بياناتك وتقديم بيئة تعليمية موثوقة ومحمية وفق أعلى المعايير العالمية.',
    subtitle_en: 'At Coach Space, we are committed to protecting your personal data and ensuring a secure, trusted learning experience.',
    lastUpdatedDate_ar: '9 سبتمبر 2026',
    lastUpdatedDate_en: 'September 9, 2026',
    contactTitle_ar: 'هل لديك استفسار حول الخصوصية؟',
    contactTitle_en: 'Have Questions About Privacy?',
    contactDescription_ar: 'فريق حماية البيانات في Coach Space مستعد للإجابة على جميع تساؤلاتك ومساعدتك في أي وقت.',
    contactDescription_en: 'Our dedicated Data Protection team is here to assist you with any privacy questions or requests.',
    contactEmail: 'coachspace4@gmail.com',
    sections: [
      {
        id: 'introduction',
        icon: 'Shield',
        title_ar: '1. مقدمة والتزامنا بالخصوصية',
        title_en: '1. Introduction & Our Privacy Commitment',
        content_ar: 'مرحباً بكم في منصة Coach Space. نولي خصوصية بياناتكم وأمانها اهتماماً بالغاً. توضح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا وحمايتنا لبياناتك الشخصية عند استخدام منصتنا التعليمية وموقعنا وتطبيقاتنا.\n\nباستخدامك للمنصة، فإنك توافق على الممارسات الموضحة في هذه السياسة. إذا كانت لديك أي استفسارات، يمكنك التواصل معنا في أي وقت.',
        content_en: 'Welcome to Coach Space. We are committed to protecting your privacy and ensuring transparency regarding how your personal information is handled across our education platform, websites, and applications.\n\nBy accessing or using Coach Space, you agree to the collection and use of information in accordance with this Privacy Policy.',
      },
      {
        id: 'collection',
        icon: 'Database',
        title_ar: '2. البيانات التي نقوم بجمعها',
        title_en: '2. Information We Collect',
        content_ar: 'نقوم بجمع البيانات الضرورية فقط لتقديم تجربة تدريبية متكاملة وآمنة:\n• بيانات الحساب: الاسم الكامل، البريد الإلكتروني، كلمة المرور المشفرة، ورقم الهاتف (اختياري).\n• بيانات التعلم: الدورات التي قمت بالتسجيل فيها، التقدم في المشاهدة، الاختبارات المجتازة، والشهادات المكتسبة.\n• بيانات المدربين: المؤهلات، النبذة التعريفية، وروابط التواصل المهنية للمدربين المعتمدين.\n• البيانات التقنية: عنوان الـ IP، نوع المتصفح، نظام التشغيل، وملفات تعريف الارتباط الضرورية لتوثيق الدخول وحفظ الجلسة.',
        content_en: 'We collect only the data necessary to provide you with a world-class, seamless learning experience:\n• Account Information: Your full name, email address, securely hashed passwords, and optional contact details.\n• Learning Records: Enrolled courses, video progress, quiz results, and verified completion certificates.\n• Instructor Profiles: Certifications, biography, expertise, and professional links for verified coaches.\n• Technical Data: IP address, device type, browser specifications, and essential session authentication cookies.',
      },
      {
        id: 'usage',
        icon: 'UserCheck',
        title_ar: '3. كيف نستخدم بياناتك الشخصية',
        title_en: '3. How We Use Your Information',
        content_ar: 'تُستخدم معلوماتكم لأغراض مشروعة ومحددة تشمل:\n• توفير إمكانية الوصول إلى الدورات والمحتوى التدريبي وتفعيل الدروس فوراً بعد الشراء.\n• إصدار الشهادات الرسمية والتحقق من صحتها عبر رمز التحقق المخصص.\n• إرسال الإشعارات الضرورية المتعلقة بحسابك، مثل استعادة كلمة المرور وتحديثات الدورات.\n• تحسين أداء واستقرار المنصة وتطوير المحتوى التعليمي.\n• حماية المنصة من محاولات الاحتيال أو الاستخدام غير المصرح به.',
        content_en: 'Your information is used strictly for legitimate educational and operational purposes:\n• Granting immediate access to training materials, lessons, and course updates upon enrollment.\n• Issuing verifiable digital certificates of completion with unique validation IDs.\n• Sending critical account-related communications such as password resets and enrollment confirmations.\n• Maintaining high platform availability, speed, security, and content quality.\n• Preventing unauthorized access and fraudulent transactions.',
      },
      {
        id: 'payments',
        icon: 'Lock',
        title_ar: '4. معلومات الدفع وأمان المعاملات المالية',
        title_en: '4. Payment Security & Financial Data',
        content_ar: 'معالجة آمنة بنسبة 100%: نحن لا نقوم بتخزين أي بيانات حساسة لبطاقات الائتمان (مثل رقم البطاقة أو رمز CVV) على خوادمنا.\n\nتتم معالجة جميع المدفوعات المالية عبر بوابة Stripe العالمية المعتمدة والمتوافقة مع أعلى معايير الأمان المصرفي العالمية (PCI-DSS المستوى الأول)، باستخدام تشفير 256-Bit SSL لضمان الحماية الكاملة لمعاملاتك.',
        content_en: '100% Secure Processing: We do not store credit card numbers, CVV codes, or full payment credentials on Coach Space servers.\n\nAll financial transactions are processed through Stripe, certified to PCI-DSS Level 1 (the highest standard in payment security), utilizing end-to-end 256-bit bank-grade SSL encryption.',
      },
      {
        id: 'cookies',
        icon: 'Eye',
        title_ar: '5. ملفات تعريف الارتباط (Cookies)',
        title_en: '5. Cookies & Session Technologies',
        content_ar: 'نستخدم ملفات تعريف الارتباط الأساسية لتمكينك من تسجيل الدخول بأمان، وحفظ لغتك المفضلة (العربية أو الإنجليزية)، والحفاظ على عناصر سلة التسوق الخاصة بك. يمكنك إدارة تفضيلات ملفات تعريف الارتباط من خلال إعدادات المتصفح الخاص بك في أي وقت.',
        content_en: 'We employ essential cookies to keep you safely logged in, remember your preferred language (English or Arabic), and preserve courses in your shopping cart. You can configure your browser to decline non-essential cookies at any time.',
      },
      {
        id: 'rights',
        icon: 'FileText',
        title_ar: '6. حقوقك وخياراتك في بياناتك',
        title_en: '6. Your Rights & Data Choices',
        content_ar: 'يحق لك في أي وقت:\n• الوصول إلى نسختك من البيانات المسجلة في حسابك ومراجعتها.\n• تعديل بيانات ملفك الشخصي عبر صفحة إعدادات الحساب.\n• طلب حذف حسابك وبياناتك الشخصية بشكل نهائي من خلال التواصل مع الدعم الفني.',
        content_en: 'Depending on your location, you hold full rights over your data, including:\n• Requesting a full copy of your personal data stored on our platform.\n• Updating and correcting your profile via Account Settings.\n• Requesting account closure and permanent deletion of personal details by contacting support.',
      },
    ],
  },
  terms: {
    badge_ar: 'اتفاقية الاستخدام الرسمية',
    badge_en: 'Official Agreement',
    title_ar: 'شروط وأحكام الاستخدام',
    title_en: 'Terms of Service',
    subtitle_ar: 'شروط وأحكام استخدام منصة Coach Space وحقوق وواجبات الطلاب والمدربين المعتمدين.',
    subtitle_en: 'Terms and conditions governing the use of the Coach Space platform for students and certified mentors.',
    lastUpdatedDate_ar: '9 سبتمبر 2026',
    lastUpdatedDate_en: 'September 9, 2026',
    contactTitle_ar: 'استفسارات قانونية أو شروط الاستخدام؟',
    contactTitle_en: 'Legal Questions or Inquiries?',
    contactDescription_ar: 'يمكنك التواصل مع الإدارة القانونية لمنصة Coach Space للحصول على أي توضيحات بخصوص شروط الخدمة.',
    contactDescription_en: 'Contact our legal compliance team for any clarifications regarding our platform terms.',
    contactEmail: 'coachspace4@gmail.com',
    sections: [
      {
        id: 'acceptance',
        icon: 'CheckCircle2',
        title_ar: '1. الموافقة على الشروط',
        title_en: '1. Acceptance of Terms',
        content_ar: 'من خلال إنشاء حساب أو شراء دورة تدريبية أو تصفح منصة Coach Space، فإنك تقر بأنك قرأت وفهمت ووافقت على الالتزام بجميع هذه الشروط والأحكام. إذا كنت لا توافق على أي جزء منها، يُرجى عدم استخدام المنصة.',
        content_en: 'By creating an account, purchasing an online course, or accessing Coach Space, you acknowledge that you have read, understood, and agreed to be legally bound by these Terms of Service. If you disagree with any portion, please discontinue platform use.',
      },
      {
        id: 'accounts',
        icon: 'UserCheck',
        title_ar: '2. الحسابات والأمان',
        title_en: '2. Account Registration & Security',
        content_ar: 'عند التسجيل، يجب عليك تقديم معلومات صحيحة ودقيقة وكاملة:\n• أنت مسؤول بالكامل عن الحفاظ على سرية كلمة المرور الخاصة بحسابك.\n• لا يجوز مشاركة الحساب أو بيانات تسجيل الدخول مع أي أطراف أخرى.\n• يجب إخطارنا فوراً في حال الاشتباه بأي دخول غير مصرح به إلى حسابك.',
        content_en: 'When registering an account, you must provide true, current, and complete information:\n• You are solely responsible for maintaining the confidentiality of your login credentials.\n• Account sharing, reselling, or credential pooling is strictly prohibited.\n• You must immediately notify Coach Space of any suspected security breach or unauthorized access.',
      },
      {
        id: 'license',
        icon: 'BookOpen',
        title_ar: '3. الوصول إلى الدورات وحقوق المشاهدة',
        title_en: '3. Course Access & Learning License',
        content_ar: 'عند شراء دورة تدريبية على منصة Coach Space، تمنحك المنصة ترخيصاً شخصياً للوصول إلى محتوى الدورة ومشاهدته لغايات التعلم الشخصي:\n• يحظر تماماً تنزيل أو إعادة بيع أو مشاركة أو تسجيل مقاطع الفيديو لأغراض تجارية.\n• المحتوى التدريبي محمي بموجب قوانين الملكية الفكرية وحقوق النشر الدولية.',
        content_en: 'Upon purchasing a course, Coach Space grants you a personal license to view and complete the course materials solely for individual educational purposes:\n• Redistribution, commercial broadcasting, video ripping, or copying is strictly illegal.\n• All video lectures, downloadable guides, and exercises remain protected by international copyright laws.',
      },
      {
        id: 'certificates',
        icon: 'Award',
        title_ar: '4. الشهادات الرقمية المعتمدة',
        title_en: '4. Verified Certificates of Completion',
        content_ar: 'تُمنح شهادة الإتمام الرقمية الرسمية فقط للطلاب الذين أكملوا مشاهدة كافة دروس الدورة واجتازوا متطلبات التقييم المحددة بنجاح. تحمل كل شهادة رمز تحقق رقمي فريد وموثوق.',
        content_en: 'Official digital certificates are issued only after verified 100% completion of course lessons and passing any required assessments. Each certificate contains a unique validation identifier verifiable on our platform.',
      },
      {
        id: 'conduct',
        icon: 'ShieldAlert',
        title_ar: '5. قواعد السلوك ومنع الانتهاكات',
        title_en: '5. Platform Code of Conduct',
        content_ar: 'يلتزم جميع المستخدمين (طلاباً ومدربين) بالسلوك المهني المحترم:\n• يمنع نشر أي محتوى مسيء، تشهيري، أو ينتهك حقوق الآخرين.\n• يحظر استخدام روبوتات تجريف البيانات (Scrapers) أو محاولة اختراق الخوادم.\n• تحتفظ Coach Space بالحق في تعليق أو حظر أي حساب ينتهك هذه المعايير دون تعويض.',
        content_en: 'All community members (students and instructors) must maintain professional, respectful interactions:\n• Harassment, abusive behavior, and discriminatory content are strictly prohibited.\n• Automated scrapers, bot attacks, and reverse engineering attempts will result in immediate termination.\n• Coach Space reserves the right to suspend any account violating these rules without refund.',
      },
    ],
  },
};

