import { GlobalBrandingConfig, LandingSectionsData } from '@/types/cms';

export const DEFAULT_BRANDING: GlobalBrandingConfig = {
  logoUrl: '/images/logo.png',
  faviconUrl: '/favicon.ico',
  siteNameAr: 'كوتش سبيس',
  siteNameEn: 'Coach Space',
  colors: {
    primaryMain: '#0F5244',
    primaryDark: '#07382E',
    primaryLight: '#10B981',
    secondaryLight: '#D1FAE5',
    accentMint: '#34D399',
  },
  buttonRadius: '12px',
  updatedAt: new Date().toISOString(),
  updatedBy: 'system',
};

export const DEFAULT_LANDING_SECTIONS: LandingSectionsData = {
  hero: {
    badge_ar: 'المنصة الرائدة في تمكين الكفاءات',
    badge_en: 'Leading Platform for Career Mastery',
    title_ar: 'انطلق في مسارك نحو',
    title_en: 'Elevate Your Career to',
    highlighted_text_ar: 'الاحتراف والريادة',
    highlighted_text_en: 'True Mastery',
    description_ar: 'اكتشف دورات تدريبية عملية يقودها نخبة من الخبراء والمعتمدين لمساعدتك في بناء مهارات المستقبل وتحقيق أهدافك المهنية.',
    description_en: 'Explore practical, industry-accredited courses led by certified leaders to help you build in-demand skills and accelerate your career.',
    cta_primary_text_ar: 'استكشف الدورات',
    cta_primary_text_en: 'Explore Courses',
    cta_primary_link: '/courses',
    cta_secondary_text_ar: 'انضم كمدرب',
    cta_secondary_text_en: 'Become an Instructor',
    cta_secondary_link: '/become-instructor',
    hero_image_url: '/images/hero-coach.png',
  },
  top_categories: {
    title_ar: 'استكشف أبرز المجالات',
    title_en: 'Top In-Demand Categories',
    subtitle_ar: 'تصفح نخبة من التخصصات المصممة لتلبية متطلبات سوق العمل العالمي.',
    subtitle_en: 'Browse our curated collection of specialized programs designed for modern industry requirements.',
    is_visible: true,
  },
  master_craft: {
    heading_ar: 'طريقك نحو الإتقان العملي والتميز الوظيفي',
    heading_en: 'Master Practical Craft & Executive Growth',
    description_ar: 'منهجية تدريب تركز على التطبيق العملي وبناء مشاريع واقعية تمنحك ميزة تنافسية حقيقية.',
    description_en: 'Practical methodology focused on real-world projects that give you a tangible edge in the marketplace.',
    features: [
      {
        id: 'feat-1',
        title_ar: 'مشاريع حقيقية معتمدة',
        title_en: 'Accredited Capstone Projects',
        desc_ar: 'قم ببناء محفظة أعمالك المهنية أثناء التعلم من خلال مشاريع حقيقية يتم تقييمها من قِبل خبراء.',
        desc_en: 'Build your verified professional portfolio during study through real-world projects reviewed by industry leaders.',
        icon: 'Award',
      },
      {
        id: 'feat-2',
        title_ar: 'إرشاد وتوجيه فردي',
        title_en: '1-on-1 Mentorship',
        desc_ar: 'تواصل مباشر وجلسات توجيهية مع مدربين متخصصين لتسريع مسار تعلمك.',
        desc_en: 'Direct access and dedicated guidance sessions with certified coaches to accelerate your learning trajectory.',
        icon: 'Users',
      },
      {
        id: 'feat-3',
        title_ar: 'شهادات إتمام موثقة رقمياً',
        title_en: 'Verifiable Digital Credentials',
        desc_ar: 'احصل على شهادات قابلة للتحقق ومشاركتها مع جهات التوظيف وLinkedIn بنقرة واحدة.',
        desc_en: 'Earn digitally authenticated certificates verifiable by recruiters and shareable on LinkedIn with one click.',
        icon: 'ShieldCheck',
      },
    ],
  },
  why_stands_out: {
    title_ar: 'لماذا تختار منصة كوتش سبيس؟',
    title_en: 'Why Choose Coach Space?',
    subtitle_ar: 'صممنا بيئة متكاملة تجمع بين سهولة التجربة، عمق المحتوى، والمرونة التامة.',
    subtitle_en: 'Engineered from the ground up to deliver seamless learning, deep expertise, and maximum flexibility.',
    cards: [
      {
        id: 'card-1',
        title_ar: 'مرونة التعلم الذاتي',
        title_en: 'Self-Paced Flexibility',
        desc_ar: 'تعلم في أي وقت ومن أي جهاز بجودة عالية وتجربة مستخدم سلسة.',
        desc_en: 'Study on your own schedule across any device with a fluid, distraction-free interface.',
        icon: 'Clock',
      },
      {
        id: 'card-2',
        title_ar: 'مجتمع شغوف ونشط',
        title_en: 'Vibrant Peer Community',
        desc_ar: 'تبادل الخبرات وتواصل مع شبكة واسعة من المتعلمين والمهنيين.',
        desc_en: 'Collaborate and network with fellow ambitious professionals worldwide.',
        icon: 'Sparkles',
      },
      {
        id: 'card-3',
        title_ar: 'محتوى متجدد باستمرار',
        title_en: 'Constantly Updated Curriculum',
        desc_ar: 'تحديثات دورية للمسارات التعليمية لضمان مواكبة أحدث التقنيات والمعايير.',
        desc_en: 'Continuous curriculum updates ensuring alignment with modern tools and industry standards.',
        icon: 'TrendingUp',
      },
    ],
  },
  real_stories: {
    title_ar: 'قصص نجاح من واقع التجربة',
    title_en: 'Real Stories from Our Learners',
    subtitle_ar: 'آراء وتجارب ملهمة من خريجين ارتقوا بمساراتهم المهنية معنا.',
    subtitle_en: 'Inspiring achievements and testimonials from alumni who transformed their careers.',
    testimonials: [
      {
        id: 't-1',
        name_ar: 'سارة المنصوري',
        name_en: 'Sara Al-Mansouri',
        role_ar: 'مديرة تسويق رقمي',
        role_en: 'Senior Digital Marketing Lead',
        quote_ar: 'المحتوى العملي والمشاريع الواقعية ساعدتني على الترقية وتولي قيادة الفريق خلال 4 أشهر فقط!',
        quote_en: 'The practical capstones and mentor feedback enabled me to step into a leadership role within 4 months!',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 't-2',
        name_ar: 'عمر الهاشمي',
        name_en: 'Omar Al-Hashemi',
        role_ar: 'مطور برمجيات سحابية',
        role_en: 'Cloud Software Engineer',
        quote_ar: 'التوجيه المباشر وجودة المنهاج كانت نقطة التحول الحقيقية في فهمي للأنظمة الموزعة.',
        quote_en: 'The direct feedback from coaches was the defining breakthrough in mastering distributed architectures.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 't-3',
        name_ar: 'ليلى الكردي',
        name_en: 'Layla Al-Kurdi',
        role_ar: 'مصممة تجربة مستخدم',
        role_en: 'Product Designer',
        quote_ar: 'أفضل استثمار قمت به في مسيرتي، الشهادة الموثقة نالت ثقة الشركات العالمية فوراً.',
        quote_en: 'Best investment in my growth; the authenticated credential gave me instant credibility with employers.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      },
    ],
  },
  faq: {
    title_ar: 'الأسئلة الشائعة',
    title_en: 'Frequently Asked Questions',
    subtitle_ar: 'إليك إجابات لأهم الاستفسارات حول الدورات وطريقة التعلم والشهادات.',
    subtitle_en: 'Clear answers to common questions about courses, learning experience, and certificates.',
    items: [
      {
        id: 'faq-1',
        question_ar: 'كيف أبدأ التعلم في منصة كوتش سبيس؟',
        question_en: 'How do I start learning on Coach Space?',
        answer_ar: 'يمكنك إنشاء حساب مجاناً، تصفح الكتالوج، واختيار الدورة المناسبة والبدء فوراً في حضور الدروس التفاعلية.',
        answer_en: 'Simply register for a free account, explore the catalog, enroll in your chosen course, and start learning immediately.',
      },
      {
        id: 'faq-2',
        question_ar: 'هل الشهادات الصادرة معتمدة وموثقة؟',
        question_en: 'Are certificates officially accredited and verifiable?',
        answer_ar: 'نعم، تصدر المنصة شهادة إتمام رقمية برمز تحقق فريد (QR Code ورقم تسلسلي) يمكن لأي جهة توظيف التحقق من صحتها فوراً.',
        answer_en: 'Yes, every completed course awards a tamper-proof credential with a unique verification code and QR code for employers.',
      },
      {
        id: 'faq-3',
        question_ar: 'هل يمكنني استرجاع الرسوم إذا لم تناسبني الدورة؟',
        question_en: 'What is the refund policy?',
        answer_ar: 'نعم، نقدم ضمان استرجاع كامل الرسوم خلال 14 يوماً من تاريخ الشراء في حال عدم تجاوز نسبة معينة من المحتوى.',
        answer_en: 'Yes, we offer a 14-day money-back guarantee if you have not completed more than the trial portion of the coursework.',
      },
      {
        id: 'faq-4',
        question_ar: 'كيف يمكنني الانضمام كمدرب وتقديم دوراتي؟',
        question_en: 'How can I join as an instructor?',
        answer_ar: 'يمكنك الضغط على زر "انضم كمدرب" وتعبئة الطلب وتقديم نبذة عن خبراتك، وسيتواصل معك فريقنا لاعتماد حسابك وبدء رفع الكورسات.',
        answer_en: 'Click "Become an Instructor", submit your credentials and experience, and our team will review and approve your studio access.',
      },
    ],
  },
  join_future: {
    title_ar: 'هل أنت مستعد لبدء خطوتك القادمة؟',
    title_en: 'Ready to Take Your Next Giant Leap?',
    subtitle_ar: 'انضم اليوم إلى آلاف المتعلمين والخبراء وابدأ في كتابة قصة نجاحك الجديدة.',
    subtitle_en: 'Join thousands of ambitious professionals and start shaping your success today.',
    button_text_ar: 'ابدأ التعلم الآن مجاناً',
    button_text_en: 'Get Started for Free',
    button_link: '/register',
  },
};
