import { Course } from "@/types/catalog";

export const MOCK_COURSES: Course[] = [
  // ==================== 1. MANAGEMENT (الإدارة) ====================
  {
    id: "course-1",
    title: "Advanced Team Leadership Strategies",
    titleAr: "استراتيجيات قيادة الفرق المتقدمة",
    category: "Management",
    categoryAr: "الإدارة",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    instructorName: "Dr. Sarah Jenkins",
    instructorNameAr: "د. سارة جينكينز",
    rating: 4.8,
    reviewsCount: 1200,
    reviewsCountFormatted: "1.2k",
    price: 89.99,
    priceFormatted: "$89.99",
    durationHours: 8,
    durationFormatted: "8 hours",
    level: "Intermediate",
    language: "English",
    isSaved: false,
  },
  {
    id: "course-5",
    title: "Agile Project Management Masterclass",
    titleAr: "الماستر كلاس في إدارة المشاريع المرنة Agile",
    category: "Management",
    categoryAr: "الإدارة",
    badge: "Popular",
    badgeAr: "شائع",
    coverImage: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
    instructorName: "Amira Al-Mansoor",
    instructorNameAr: "أميرة المنصور",
    rating: 4.7,
    reviewsCount: 1420,
    reviewsCountFormatted: "1.4k",
    price: 74.99,
    priceFormatted: "$74.99",
    durationHours: 6,
    durationFormatted: "6 hours",
    level: "Intermediate",
    language: "Arabic",
    isSaved: false,
  },

  // ==================== 2. COMMUNICATION (التواصل) ====================
  {
    id: "course-2",
    title: "Mastering Difficult Conversations",
    titleAr: "إتقان المحادثات الصعبة والقيادية",
    category: "Communication",
    categoryAr: "التواصل",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    instructorName: "Marcus Reed",
    instructorNameAr: "ماركوس ريد",
    rating: 4.9,
    reviewsCount: 850,
    reviewsCountFormatted: "850",
    price: 64.99,
    priceFormatted: "$64.99",
    durationHours: 4,
    durationFormatted: "4 hours",
    level: "Beginner",
    language: "English",
    isSaved: false,
  },
  {
    id: "course-11",
    title: "Public Speaking & Executive Pitching",
    titleAr: "فن الخطابة والتحدث الجماهيري للمدراء",
    category: "Communication",
    categoryAr: "التواصل",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80",
    instructorName: "Laila Al-Shami",
    instructorNameAr: "ليلى الشامي",
    rating: 4.9,
    reviewsCount: 1680,
    reviewsCountFormatted: "1.7k",
    price: 49.99,
    priceFormatted: "$49.99",
    durationHours: 5,
    durationFormatted: "5 hours",
    level: "Beginner",
    language: "Arabic",
    isSaved: true,
  },

  // ==================== 3. STRATEGY (الاستراتيجية) ====================
  {
    id: "course-12",
    title: "Corporate Strategy & Competitive Advantage",
    titleAr: "الاستراتيجية المؤسسية والميزة التنافسية",
    category: "Strategy",
    categoryAr: "الاستراتيجية",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    instructorName: "Dr. Tariq Al-Mansoor",
    instructorNameAr: "د. طارق المنصور",
    rating: 4.9,
    reviewsCount: 2400,
    reviewsCountFormatted: "2.4k",
    price: 135.00,
    priceFormatted: "$135.00",
    durationHours: 15,
    durationFormatted: "15 hours",
    level: "Advanced",
    language: "Arabic",
    isSaved: false,
  },
  {
    id: "course-22",
    title: "Business Model Canvas & Value Proposition",
    titleAr: "تصميم نموذج العمل التجاري والقيمة المضافة",
    category: "Strategy",
    categoryAr: "الاستراتيجية",
    badge: "Popular",
    badgeAr: "شائع",
    coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
    instructorName: "Huda Al-Zahrani",
    instructorNameAr: "هدى الزهراني",
    rating: 4.8,
    reviewsCount: 1350,
    reviewsCountFormatted: "1.3k",
    price: 0,
    priceFormatted: "Free",
    durationHours: 5,
    durationFormatted: "5 hours",
    level: "Beginner",
    language: "Arabic",
    isSaved: false,
  },

  // ==================== 4. LEADERSHIP (القيادة) ====================
  {
    id: "course-4",
    title: "Executive Leadership & Emotional Intelligence",
    titleAr: "القيادة التنفيذية والذكاء العاطفي",
    category: "Leadership",
    categoryAr: "القيادة",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
    instructorName: "Prof. David Miller",
    instructorNameAr: "أ.د. ديفيد ميلر",
    rating: 4.9,
    reviewsCount: 2150,
    reviewsCountFormatted: "2.1k",
    price: 99.99,
    priceFormatted: "$99.99",
    durationHours: 10,
    durationFormatted: "10 hours",
    level: "Advanced",
    language: "English",
    isSaved: true,
  },
  {
    id: "course-13",
    title: "Adaptive Leadership in Times of Change",
    titleAr: "القيادة التكيفية في أوقات التغير المستمر",
    category: "Leadership",
    categoryAr: "القيادة",
    coverImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
    instructorName: "Dr. Noura Al-Otaibi",
    instructorNameAr: "د. نورة العتيبي",
    rating: 4.8,
    reviewsCount: 890,
    reviewsCountFormatted: "890",
    price: 85.00,
    priceFormatted: "$85.00",
    durationHours: 7,
    durationFormatted: "7 hours",
    level: "Intermediate",
    language: "Arabic",
    isSaved: false,
  },

  // ==================== 5. MARKETING (التسويق) ====================
  {
    id: "course-14",
    title: "Digital Marketing & Performance Ads 2026",
    titleAr: "التسويق الرقمي والإعلانات ممتازة الأداء",
    category: "Marketing",
    categoryAr: "التسويق",
    badge: "Popular",
    badgeAr: "شائع",
    coverImage: "https://images.unsplash.com/photo-1533750516457-a7f992034fec?auto=format&fit=crop&w=800&q=80",
    instructorName: "Jessica Taylor",
    instructorNameAr: "جيسيكا تايلور",
    rating: 4.7,
    reviewsCount: 1540,
    reviewsCountFormatted: "1.5k",
    price: 79.99,
    priceFormatted: "$79.99",
    durationHours: 11,
    durationFormatted: "11 hours",
    level: "Beginner",
    language: "English",
    isSaved: false,
  },
  {
    id: "course-26",
    title: "Social Media Brand Strategy & Viral Campaigns",
    titleAr: "استراتيجيات التسويق عبر وسائل التواصل الاجتماعي",
    category: "Marketing",
    categoryAr: "التسويق",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80",
    instructorName: "Alex Turner",
    instructorNameAr: "أليكس تيرنر",
    rating: 4.8,
    reviewsCount: 1450,
    reviewsCountFormatted: "1.5k",
    price: 88.00,
    priceFormatted: "$88.00",
    durationHours: 8,
    durationFormatted: "8 hours",
    level: "Intermediate",
    language: "English",
    isSaved: false,
  },

  // ==================== 6. DESIGN (التصميم) ====================
  {
    id: "course-7",
    title: "UI/UX Design Systems for Enterprise",
    titleAr: "أنظمة تصميم واجهات المستخدم للشركات الكبرى",
    category: "Design",
    categoryAr: "التصميم",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
    instructorName: "Sophia Martinez",
    instructorNameAr: "سوفيا مارتينيز",
    rating: 4.9,
    reviewsCount: 3100,
    reviewsCountFormatted: "3.1k",
    price: 94.99,
    priceFormatted: "$94.99",
    durationHours: 14,
    durationFormatted: "14 hours",
    level: "Advanced",
    language: "English",
    isSaved: false,
  },
  {
    id: "course-15",
    title: "Figma Masterclass: Prototyping & Micro-interactions",
    titleAr: "الاحتراف في فجما: التفاعل والأنيميشن التفاعلي",
    category: "Design",
    categoryAr: "التصميم",
    badge: "New",
    badgeAr: "جديد",
    coverImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    instructorName: "Karim Abdel-Fattah",
    instructorNameAr: "كريم عبد الفتاح",
    rating: 4.8,
    reviewsCount: 760,
    reviewsCountFormatted: "760",
    price: 59.99,
    priceFormatted: "$59.99",
    durationHours: 8,
    durationFormatted: "8 hours",
    level: "Intermediate",
    language: "Arabic",
    isSaved: false,
  },

  // ==================== 7. DEVELOPMENT (البرمجة والتطوير) ====================
  {
    id: "course-9",
    title: "Full-Stack Web Development Architecture",
    titleAr: "هندسة وتطوير تطبيقات الويب المتكاملة",
    category: "Development",
    categoryAr: "البرمجة والتطوير",
    coverImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    instructorName: "Alex Rivera",
    instructorNameAr: "أليكس ريفيرا",
    rating: 4.8,
    reviewsCount: 1890,
    reviewsCountFormatted: "1.8k",
    price: 129.99,
    priceFormatted: "$129.99",
    durationHours: 18,
    durationFormatted: "18 hours",
    level: "Advanced",
    language: "English",
    isSaved: false,
  },
  {
    id: "course-16",
    title: "Next.js 15 & React 19 Fullstack Masterclass",
    titleAr: "تطوير تطبيقات الويب الحديثة باستخدام Next.js 15",
    category: "Development",
    categoryAr: "البرمجة والتطوير",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80",
    instructorName: "Dr. Tariq Al-Mansoor",
    instructorNameAr: "د. طارق المنصور",
    rating: 4.9,
    reviewsCount: 3420,
    reviewsCountFormatted: "3.4k",
    price: 89.00,
    priceFormatted: "$89.00",
    durationHours: 16,
    durationFormatted: "16 hours",
    level: "Intermediate",
    language: "Arabic",
    isSaved: true,
  },

  // ==================== 8. DATA SCIENCE (علوم البيانات) ====================
  {
    id: "course-32",
    title: "Python for Data Analysis & Statistical Modeling",
    titleAr: "تحليل البيانات والنمذجة الإحصائية بلغة بايثرن",
    category: "Data Science",
    categoryAr: "علوم البيانات",
    badge: "Bestseller",
    badgeAr: "الأكثر مبيعاً",
    coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    instructorName: "Chris Hemsworth",
    instructorNameAr: "كريس هيمسورث",
    rating: 4.9,
    reviewsCount: 2890,
    reviewsCountFormatted: "2.9k",
    price: 79.99,
    priceFormatted: "$79.99",
    durationHours: 10,
    durationFormatted: "10 hours",
    level: "Intermediate",
    language: "English",
    isSaved: true,
  }
];

export const TOTAL_MOCK_RESULTS_COUNT = 15;
